apiVersion: certmanager.io/v1alpha1
kind: Certificate
metadata:
  name: jamiemun-com-tls
spec:
  secretName: jamiemun-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: jamiemun.com
  dnsNames:
    - jamiemun.com
    - www.jamiemun.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - jamiemun.com
          - www.jamiemun.com